apiVersion: v1
kind: Service
metadata:
  name: { { .Values.svc.name } }
spec:
  type: ClusterIP
  selector:
    app: { { .Values.deployment.name } }
    version: '1.0'
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
