apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
  labels:
    app: finance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-app
      version: 'v2.0.0'
  template:
    metadata:
      labels:
        app: finance-app
        version: 'v2.0.0'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9101'
    spec:
      containers:
        - name: finance-app
          image: chrisbarnes2000/ccms-project2
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: v2.0.0
          ports:
            - name: http
              containerPort: 8080
            - name: probe
              containerPort: 8086
            - name: flask
              containerPort: 5000
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /live
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: probe
            periodSeconds: 5
