name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees: your_username
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support-docs]
          required: true
        - label: I read the [contributing-guide]
          required: true
        - label: I searched [issues] and couldn’t find anything (or linked relevant results below)
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        How did this happen? Please provide a [minimal, reproducible example].
        **To Reproduce**
        Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
      placeholder: Tell us what you see!
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen? A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - "1"
        - "2"
        - Other
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      # - label: I agree to follow the [code-of-conduct]
      description: By submitting this issue, you agree to follow our [code-of-conduct]
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

# <!-- Definitions/Links -->

# <!-- External Based -->

[cs]: https://codesandbox.io
[rubberduck]: https://rubberduckdebugging.com
[understanding-good-commit-message]: https://chris.beams.io/posts/git-commit
[xy]: https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem/66378#66378
[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
[steps-to-contribute]: https://www.dataschool.io/how-to-contribute-on-github/#gettingstarted

# <!-- Repo Based -->

[author]: https://YOUR-Domain.com
[repo]: https://github.com/YOUR-ORGANIZATION/YOUR-REPO

[wiki]: [repo]/wiki
[discussions]: [repo]/discussions
[curr-branch]: [repo]/blob/main
[.github]: [curr-branch]/.github

[license]: [.github]/LICENSE
[support-docs]: [.github]/Support.md
[code-of-conduct]: [.github]/Code-of-conduct.md
[contributing-guide]: [.github]/Contributing.md

# <!-- [ideas]: https://github.com/YOUR-ORGANIZATION/ideas -->

[search-github-issues]: https://github.com/type=Issues&search?q=user%3AYOUR-ORGANIZATION
[issues]: https://github.com/YOUR-ORGANIZATION/YOUR-REPO/issues
[reporting-issues]: [issues]/new

# <!-- Definitions/Links END -->
