apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-stable
  namespace: 
spec:
  rules:
  - host: hotel.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: hotel-svc-stable
          servicePort: 80